export const ErrorCodes = Object.freeze({
  RAW_MATERIAL_ID_REQUIRED: 'RAW_MATERIAL_ID_REQUIRED',
  RAW_MATERIAL_NAME_REQUIRED: 'RAW_MATERIAL_NAME_REQUIRED',
  RAW_MATERIAL_DUPLICATE_NAME: 'RAW_MATERIAL_DUPLICATE_NAME',
  PURCHASE_QUANTITY_REQUIRED: 'PURCHASE_QUANTITY_REQUIRED',
  PURCHASE_QUANTITY_INVALID: 'PURCHASE_QUANTITY_INVALID',
  PURCHASE_UNIT_REQUIRED: 'PURCHASE_UNIT_REQUIRED',
  PURCHASE_PRICE_REQUIRED: 'PURCHASE_PRICE_REQUIRED',
  PURCHASE_PRICE_INVALID: 'PURCHASE_PRICE_INVALID',
  PURCHASE_PRICE_USD_REQUIRED: 'PURCHASE_PRICE_USD_REQUIRED',
  PURCHASE_PRICE_LBP_REQUIRED: 'PURCHASE_PRICE_LBP_REQUIRED',
  COST_PER_UNIT_USD_REQUIRED: 'COST_PER_UNIT_USD_REQUIRED',
  COST_PER_UNIT_LBP_REQUIRED: 'COST_PER_UNIT_LBP_REQUIRED',
  BASE_UNIT_UNSUPPORTED: 'BASE_UNIT_UNSUPPORTED',
  PURCHASE_UNIT_UNSUPPORTED: 'PURCHASE_UNIT_UNSUPPORTED',
  CUSTOM_CONVERSION_INVALID: 'CUSTOM_CONVERSION_INVALID',
  TIMESTAMP_INVALID: 'TIMESTAMP_INVALID',
  CURRENCY_UNSUPPORTED: 'CURRENCY_UNSUPPORTED',
  EXCHANGE_RATE_INVALID: 'EXCHANGE_RATE_INVALID',
  FORMULA_MULTIPLIER_INVALID: 'FORMULA_MULTIPLIER_INVALID',
  UNIT_CONVERSION_MISSING: 'UNIT_CONVERSION_MISSING',
  RAW_MATERIAL_NOT_FOUND: 'RAW_MATERIAL_NOT_FOUND',
  PRODUCT_ID_REQUIRED: 'PRODUCT_ID_REQUIRED',
  PRODUCT_NAME_REQUIRED: 'PRODUCT_NAME_REQUIRED',
  PRODUCT_INGREDIENTS_REQUIRED: 'PRODUCT_INGREDIENTS_REQUIRED',
  INGREDIENT_MATERIAL_REQUIRED: 'INGREDIENT_MATERIAL_REQUIRED',
  INGREDIENT_QUANTITY_REQUIRED: 'INGREDIENT_QUANTITY_REQUIRED',
  INGREDIENT_QUANTITY_INVALID: 'INGREDIENT_QUANTITY_INVALID',
  INGREDIENT_UNIT_REQUIRED: 'INGREDIENT_UNIT_REQUIRED',
  INGREDIENT_DUPLICATE_RAW_MATERIAL: 'INGREDIENT_DUPLICATE_RAW_MATERIAL',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  SETTINGS_CURRENCY_REQUIRED: 'SETTINGS_CURRENCY_REQUIRED',
  SETTINGS_DATA_FOLDER_REQUIRED: 'SETTINGS_DATA_FOLDER_REQUIRED',
  SETTINGS_APP_VERSION_REQUIRED: 'SETTINGS_APP_VERSION_REQUIRED',
  USERNAME_REQUIRED: 'USERNAME_REQUIRED',
  PASSWORD_REQUIRED: 'PASSWORD_REQUIRED',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_INACTIVE: 'USER_INACTIVE',
  LOGIN_INVALID: 'LOGIN_INVALID',
  ADMIN_KEY_INVALID: 'ADMIN_KEY_INVALID',
  MISSING_RAW_MATERIAL: 'MISSING_RAW_MATERIAL',
  RAW_MATERIAL_IN_USE: 'RAW_MATERIAL_IN_USE',
  FILE_MISSING: 'FILE_MISSING',
  FILE_INVALID_JSON: 'FILE_INVALID_JSON',
  FILE_SAVE_ERROR: 'FILE_SAVE_ERROR',
  FILE_READ_ERROR: 'FILE_READ_ERROR'
});

export const ErrorMessages = Object.freeze({
  [ErrorCodes.RAW_MATERIAL_ID_REQUIRED]: 'Raw material data is missing its ID.',
  [ErrorCodes.RAW_MATERIAL_NAME_REQUIRED]: 'Enter a raw material name.',
  [ErrorCodes.RAW_MATERIAL_DUPLICATE_NAME]: 'A raw material with this name already exists.',
  [ErrorCodes.PURCHASE_QUANTITY_REQUIRED]: 'Raw material data is missing its purchase quantity.',
  [ErrorCodes.PURCHASE_QUANTITY_INVALID]: 'Enter a purchase quantity greater than zero.',
  [ErrorCodes.PURCHASE_UNIT_REQUIRED]: 'Raw material data is missing its purchase unit.',
  [ErrorCodes.PURCHASE_PRICE_REQUIRED]: 'Enter a purchase price.',
  [ErrorCodes.PURCHASE_PRICE_INVALID]: 'Enter a purchase price that is zero or greater.',
  [ErrorCodes.PURCHASE_PRICE_USD_REQUIRED]: 'Raw material data is missing its USD purchase price.',
  [ErrorCodes.PURCHASE_PRICE_LBP_REQUIRED]: 'Raw material data is missing its LBP purchase price.',
  [ErrorCodes.COST_PER_UNIT_USD_REQUIRED]: 'Raw material data is missing its USD cost per base unit.',
  [ErrorCodes.COST_PER_UNIT_LBP_REQUIRED]: 'Raw material data is missing its LBP cost per base unit.',
  [ErrorCodes.BASE_UNIT_UNSUPPORTED]: 'Choose a supported base unit.',
  [ErrorCodes.PURCHASE_UNIT_UNSUPPORTED]: 'Choose a supported purchase unit.',
  [ErrorCodes.CUSTOM_CONVERSION_INVALID]: 'Raw material data has an invalid custom conversion.',
  [ErrorCodes.TIMESTAMP_INVALID]: 'Saved data has an invalid timestamp.',
  [ErrorCodes.CURRENCY_UNSUPPORTED]: 'Choose USD or LBP.',
  [ErrorCodes.EXCHANGE_RATE_INVALID]: 'Enter an exchange rate greater than zero.',
  [ErrorCodes.FORMULA_MULTIPLIER_INVALID]: 'Enter a total cost multiplier greater than zero.',
  [ErrorCodes.UNIT_CONVERSION_MISSING]: 'Add the missing unit conversion for this raw material.',
  [ErrorCodes.RAW_MATERIAL_NOT_FOUND]: 'This raw material could not be found.',
  [ErrorCodes.PRODUCT_ID_REQUIRED]: 'Product data is missing its ID.',
  [ErrorCodes.PRODUCT_NAME_REQUIRED]: 'Enter a product name.',
  [ErrorCodes.PRODUCT_INGREDIENTS_REQUIRED]: 'Add at least one ingredient.',
  [ErrorCodes.INGREDIENT_MATERIAL_REQUIRED]: 'Choose a raw material for this ingredient row.',
  [ErrorCodes.INGREDIENT_QUANTITY_REQUIRED]: 'Enter a quantity for this ingredient row.',
  [ErrorCodes.INGREDIENT_QUANTITY_INVALID]: 'Enter an ingredient quantity greater than zero.',
  [ErrorCodes.INGREDIENT_UNIT_REQUIRED]: 'Choose a unit for this ingredient row.',
  [ErrorCodes.INGREDIENT_DUPLICATE_RAW_MATERIAL]: 'Use each raw material only once in a product.',
  [ErrorCodes.PRODUCT_NOT_FOUND]: 'This product could not be found.',
  [ErrorCodes.SETTINGS_CURRENCY_REQUIRED]: 'Settings data is missing currency settings.',
  [ErrorCodes.SETTINGS_DATA_FOLDER_REQUIRED]: 'Settings data is missing the data folder path.',
  [ErrorCodes.SETTINGS_APP_VERSION_REQUIRED]: 'Settings data is missing the app version.',
  [ErrorCodes.USERNAME_REQUIRED]: 'Enter a username.',
  [ErrorCodes.PASSWORD_REQUIRED]: 'Enter a password.',
  [ErrorCodes.USER_ALREADY_EXISTS]: 'user already exists.',
  [ErrorCodes.USER_NOT_FOUND]: 'This user could not be found.',
  [ErrorCodes.USER_INACTIVE]: 'This user no longer has access.',
  [ErrorCodes.LOGIN_INVALID]: 'Username or password is incorrect.',
  [ErrorCodes.ADMIN_KEY_INVALID]: 'Admin key is incorrect.',
  [ErrorCodes.MISSING_RAW_MATERIAL]: 'This product references a raw material that no longer exists.',
  [ErrorCodes.RAW_MATERIAL_IN_USE]: 'This raw material is used by a product.',
  [ErrorCodes.FILE_MISSING]: 'A required data file is missing.',
  [ErrorCodes.FILE_INVALID_JSON]: 'A data file contains invalid JSON.',
  [ErrorCodes.FILE_SAVE_ERROR]: 'The app could not save data.',
  [ErrorCodes.FILE_READ_ERROR]: 'The app could not read data.'
});

export function getErrorMessage(code) {
  return ErrorMessages[code] ?? 'Something went wrong.';
}
